import json
import os
import datetime
import enum

# Constants

ENUM_RECORD = "enum"
CLASS_RECORD = "class"
MABEL_VERSION = '0.1'
MABEL_GEN_HEADER = """/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: {version}.
 * Creation date: {date}
 * Base: {base}
 */

"""

def json_from_path(path):
    with open(path) as f:
        return json.load(f)

def open_file_path(directory, filename):
    path = os.path.join(directory, filename)
    return open(path, 'w+')

def create_base_file(directory, base, extension):
    f = open_file_path(directory, base + extension)
    header = MABEL_GEN_HEADER.format(date=str(datetime.datetime.now()),
                                    base=base,
                                    version=MABEL_VERSION)
    f.write(header)
    return f

def incr_indent(s):
    tmp = ''
    for part in s.splitlines():
        tmp += '\t' + part + '\n'
    return tmp