/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 10:59:34.204408
 * Base: Hat.json
 */

package main.models.apparel;

import java.io.Serializable;
import main.models.Color;

public class Hat implements Serializable {
	public float radius = 1.0f;
	public Color color;
}
