/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:50:33.488218
 * Base: Hat.json
 */

//md5:c90b32ba53c76ae112192c2d1f108e0b

package main.models.apparel;

import main.models.Color;
import java.io.Serializable;

public class Hat implements Serializable {
	public float radius = 1.0f;
	public Color color;
}
