/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.495782
 * Base: Hat.json
 */

package main.models.apparel;

import main.models.Color;
import java.io.Serializable;

public class Hat implements Serializable {
	public float radius = 1.0f;
	public Color color;
}
