/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:50:33.486707
 * Base: Hat.json
 */

//md5:c90b32ba53c76ae112192c2d1f108e0b

namespace Models {
	public class Hat {
		public float radius = 1.0f;
		public Color color;
	}
}
