/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.494041
 * Base: Hat.json
 */

namespace Models {
	class Hat {
		public float radius = 1.0f;
		public Color color;
	}
}
