/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.971208
 * Base: Animal
 */

using System.Collections.Generic;

namespace Models {
	class Animal : Entity {
		public int age;
		public float height;
		public List<Entity> friends;
		public string owner;
		public bool happy;
		public Color color;
	}
}
