/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.493229
 * Base: Animal.json
 *
 * Represents an animal with a hat.
 */

using System.Collections.Generic;

namespace Models {
	class Animal : Entity {
		public int age;
		public float height;
		public List<Entity> friends;
		public string owner = "John";
		public bool happy = true;
		public Color color;
		public Hat hat;
	}
}
