/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:51:24.648472
 * Base: Color.json
 */

//md5:3a8139e3d124554ea2ff03fca7bb776a

namespace Models {
	public enum Color {
		RED,
		GREEN,
		BLUE,
		PURPLE
	}
}
