/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 10:59:34.203174
 * Base: Entity.json
 */

namespace Models {
	class Entity {
	}
}
