/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.983720
 * Base: Animal
 */

package main.models;

import java.util.List;
import main.models.Entity;
import main.models.Color;

public class Animal extends Entity {
	public int age;
	public float height;
	public List<Entity> friends;
	public String owner;
	public boolean happy;
	public Color color;
}
