/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 10:59:34.203920
 * Base: Animal.json
 *
 * Represents an animal with a hat.
 */

package main.models;

import main.models.apparel.Hat;
import java.util.List;

public class Animal extends Entity {
	public int age;
	public float height;
	public List<Entity> friends;
	public String owner = "John";
	public boolean happy = true;
	public Color color;
	public Hat hat;
}
