/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:50:33.487828
 * Base: Animal.json
 *
 * Represents an animal with a hat.
 */

//md5:c9593ad9c9a653cc56d93b71d33a9740

package main.models;

import java.util.List;
import main.models.apparel.Hat;

public class Animal extends Entity {
	public int age;
	public float height;
	public List<Entity> friends;
	public String owner = "John";
	public boolean happy = true;
	public Color color;
	public Hat hat;
}
