/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.988728
 * Base: Color
 */

package main.models;

public enum Color {
	RED,
	GREEN,
	BLUE
}
