/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.494951
 * Base: Color.json
 */

package main.models;

public enum Color {
	RED,
	GREEN,
	BLUE
}
