/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.495228
 * Base: Entity.json
 */

package main.models;

import java.io.Serializable;

public class Entity implements Serializable {
}
