/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.958696
 * Base: Animal
 */

#ifndef MODELS_ANIMAL_H
#define MODELS_ANIMAL_H

#include <vector>
#include <string>
#include "Entity.h"
#include "Color.h"

namespace models {
	struct Animal : public Entity {
		uint32_t m_age;
		float m_height;
		std::vector<Entity> m_friends;
		std::string m_owner;
		bool m_happy;
		Color m_color;
	};
}

#endif //MODELS_ANIMAL_H