/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:51:24.647688
 * Base: Color.json
 */

//md5:3a8139e3d124554ea2ff03fca7bb776a

#ifndef MODELS_COLOR_H
#define MODELS_COLOR_H

#include <cstddef>

namespace models {
	enum class Color {
		RED,
		GREEN,
		BLUE,
		PURPLE
	};
	
	static const size_t ColorCount = 4;
}

#endif //MODELS_COLOR_H