/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.962700
 * Base: Color
 */

#ifndef MODELS_COLOR_H
#define MODELS_COLOR_H

namespace models {
	enum class Color {
		RED,
		GREEN,
		BLUE
	};
}

#endif //MODELS_COLOR_H