/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:09:39.736580
 * Base: Color.json
 */

#ifndef MODELS_COLOR_H
#define MODELS_COLOR_H

#include <cstddef>

namespace models {
	enum class Color {
		RED,
		GREEN,
		BLUE
	};
	
	static const size_t ColorCount = 3;
}

#endif //MODELS_COLOR_H