/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-11-18 23:28:32.966703
 * Base: Entity
 */

#ifndef MODELS_ENTITY_H
#define MODELS_ENTITY_H

namespace models {
	struct Entity {
	};
}

#endif //MODELS_ENTITY_H