/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.492497
 * Base: Entity.json
 */

#ifndef MODELS_ENTITY_H
#define MODELS_ENTITY_H

namespace models {
	struct Entity {
	};
}

#endif //MODELS_ENTITY_H