/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:50:33.482092
 * Base: Entity.json
 */

//md5:b62cbac8d179980c79734e721bc43596

#ifndef MODELS_ENTITY_H
#define MODELS_ENTITY_H

namespace models {
	struct Entity {
	};
}

#endif //MODELS_ENTITY_H