/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-02 18:43:56.492829
 * Base: Hat.json
 */

#ifndef MODELS_HAT_H
#define MODELS_HAT_H

#include "Color.h"

namespace models {
	struct Hat {
		float m_radius = 1.0f;
		Color m_color;
	};
}

#endif //MODELS_HAT_H