/*
 * WARNING! This file was autogenerated.  Do not modify it!
 * 
 * Created using github.com/federicotdn/mabel, version: 0.1.
 * Creation date: 2016-12-13 13:50:33.483412
 * Base: Hat.json
 */

//md5:c90b32ba53c76ae112192c2d1f108e0b

#ifndef MODELS_HAT_H
#define MODELS_HAT_H

#include "Color.h"

namespace models {
	struct Hat {
		float m_radius = 1.0f;
		Color m_color;
	};
}

#endif //MODELS_HAT_H